import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/manrope/latin-400.css";
import "@fontsource/manrope/latin-500.css";
import "@fontsource/manrope/latin-600.css";
import "@fontsource/manrope/latin-700.css";
import "@fontsource/manrope/latin-800.css";
import "./style.css";
import App from "./App";
import { registerSW } from "virtual:pwa-register";
registerSW({ immediate: true });
createRoot(document.getElementById("root")).render(<App />);
